### ISSUE TITLE
build is not working

### ISSUE THREAD

**Issue by Zeus-Iqd** [emersonbottero/vitepress-plugin-search#58] opened 2023-03-01 03:58 UTC
I use this plugin. when I npm run build .this is not working .
<img width="523" alt="image" src="https://user-images.githubusercontent.com/25756963/222041443-43c19a21-1fd6-4358-8c40-6c2f0c59aa4b.png">

**Comment by emersonbottero** [comment] 2023-03-07 22:09
can you share a repo?

**Comment by AfireHong** [comment] 2023-03-10 09:23
试试在vite的配置里面把build.ssr设置成false。
Try setting build.ssr to false in vite's configuration, it works in my project

**Comment by mil7** [comment] 2023-03-17 07:10
@AfireHong,
thanks for the idea to explicitely set `build.ssr` to false. This did help me as well.

@emersonbottero, is this a common issue? Shouldn't you/we mention it in the Readme?

**Comment by emersonbottero** [comment] 2023-03-19 23:31
it worked before, maybe something changed in the last vitepress version.. 
I'll do some tests first.

**Comment by shadow-light** [comment] 2023-03-21 00:11
This fixed it for me:

```ts
        async load(this, id) {
            if (id !== resolvedVirtualModuleId)
                return
            if (!computedIndex){
                // Avoid computing the index more than once
                computedIndex = await IndexSearch(config.root, options)
            }
            return computedIndex
        },
```

**Comment by shadow-light** [comment] 2023-03-21 00:12
It does seem to compute it twice still, probably due to async. But at least it works.

**Comment by joshshannon** [comment] 2023-04-16 01:55
I think #60 is a duplicate of this issue. A PR was merged to fix this issue and builds seem to be working correctly in 1.0.4-alpha.20 without the build.ssr workaround.

**Closed** 2023-05-13 21:51 UTC
Labels: bug
